server:
  port: 8083
spring:
  application:
    name: gateway-server
#  cloud:
#      gateway:
#        filter:
#          secure-headers:
#            content-type-options:

logging:
  level:
    com.yesbinary: debug
    org.springframework.web: warn

#cloud:
#    gateway:
#      filter:
#        remove-non-proxy-headers:
#          headers:
#          - dummy

