server:
  port: 8999
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://bitbucket.org/yes_binary/configuration     # 配置git仓库的地址
          search-paths: /         # git仓库地址下的相对地址，可以配置多个，用,分割。
          username: ${BITBUCKET_USERNAME}                                      # git仓库的账号
          password: ${BITBUCKET_PASSWORD}                                    # git仓库的密码
#          username: ${GITEE_USERNAME}                                      # git仓库的账号
#          password: ${GITEE_PASSWORD}                                    # git仓库的密码
  rabbitmq:
    host: localhost
    port: 5672
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1111/eureka/   ## 注册中心eurka地址


management:
  security:
     enabled: false

